swagger: '2.0'
info:
  version: 1.0.0
  title: Persons API
paths:
  /persons:
    get:
      summary: Get all persons
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Person'
    post:
      summary: Create a new person
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Person'
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/Person'
  /persons/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: integer
    get:
      summary: Get a person by ID
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Person'
      404:
        description: Person not found
    put:
      summary: Update a person by ID
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Person'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Person'
      404:
        description: Person not found
    delete:
      summary: Delete a person by ID
      responses:
        204:
          description: No Content
      404:
        description: Person not found
definitions:
  Person:
    type: object
    properties:
      id:
        type: integer
      firstName:
        type: string
      lastName:
        type: string
